

```{r}
library(ggplot2)
```



```{r}
# load datasets
merge_exp <- readRDS("~/Desktop/phd/kap1_primate/bcells_exp/expression_merge.rds")
chimp_overlap <- read.csv("../../tables/chipseq_rnaseq_overlap_chimp.csv")
oran_overlap <- read.csv("../../tables/chipseq_rnaseq_overlap_oran.csv")
```

From previous analysis, we know there are 26 overlaps position in Chimp and 5 overlaps in Orangutan.

```{r}
# calculate mean expression 
chimp_overlap_process <- chimp_overlap
chimp_overlap_process$exp <- rowMeans(chimp_overlap[, 6:14], na.rm = TRUE)
chimp_overlap_process <- chimp_overlap_process[, -(6:14)]
chimp_overlap_process$teName <- 
    sub(".*\\|.*\\|.*\\|(.*?):.*", "\\1", chimp_overlap_process$ID)

oran_overlap_process <- oran_overlap
oran_overlap_process$exp <- rowMeans(oran_overlap[, 6:14], na.rm = TRUE)
oran_overlap_process <- oran_overlap_process[, -(6:14)]
oran_overlap_process$teName <- 
    sub(".*\\|.*\\|.*\\|(.*?):.*", "\\1", oran_overlap_process$ID)

```

Then we see how many unique value of TEs are there:
```{r}
# TE ID
uniq_chimp_te <- unique(chimp_overlap_process$teName) # 14
uniq_oran_te <- unique(oran_overlap_process$teName) # 15
```


```{r}
chimp_te_exp <- merge_exp$chimp_TE_filter %>%
    filter(teName %in% uniq_chimp_te) %>%
    mutate(overlap = ifelse(ID %in% chimp_overlap_process$ID, 1, 0))

oran_te_exp <- merge_exp$oran_TE_filter %>%
    filter(teName %in% uniq_oran_te) %>%
    mutate(overlap = ifelse(ID %in% oran_overlap_process$ID, 1, 0))
```

Visualize:
```{r}
library(ggbeeswarm)

g_chimp <- ggplot(chimp_te_exp, aes(x = teName, y = log(exp))) +
  geom_quasirandom(aes(color = factor(overlap), alpha = factor(overlap)), size = 2) +
  scale_color_manual(
    values = c("0" = "blue", "1" = "red"), 
    name = "Overlap",
    labels = c("No Overlap", "Overlap")
  ) +
  scale_alpha_manual(
    values = c("0" = 0.5, "1" = 1), 
    guide = "none" 
  ) +
  labs(
    title = "Chimp",
    x = "",
    y = "Expression (Log exp)"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1), 
    legend.position = "top"
  )


g_oran <- ggplot(oran_te_exp, aes(x = teName, y = log(exp))) +
  geom_quasirandom(aes(color = factor(overlap), alpha = factor(overlap)), size = 2) +
  scale_color_manual(
    values = c("0" = "blue", "1" = "red"), 
    name = "Overlap",
    labels = c("No Overlap", "Overlap")
  ) +
  scale_alpha_manual(
    values = c("0" = 0.5, "1" = 1), 
    guide = "none" 
  ) +
  labs(
    title = "Orangutan",
    x = "",
    y = "Expression (Log exp)"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1), 
    legend.position = "top"
  )

```

```{r}
ggsave(filename = "../../figures/chimp_rnaseq_chip.jpg", g_chimp,
       dpi=400, width=7, height=4)

ggsave(filename = "../../figures/oran_rnaseq_oran.jpg", g_oran, dpi=400, width=4, height=4)
```

