# Analyze TEtranscript expression data

```{r message=FALSE}
library(dplyr)
library(tidyr)
library(tibble)
library(twice)
library(ggplot2)
```

```{r}
data <- readRDS("../../bcells_exp/tetranscriptDE.rds")
data("hmKZNFs337")
data("hg19rmsk_info")

# prepare gene list
gene_df <- hmKZNFs337
gene_df <- rbind(hmKZNFs337, c("ENSG00000130726", "KAP1"))

# prepare TE list
te_class_id <- c("SINE", "DNA", "LTR", "LINE", "SVA")
te_list <- hg19rmsk_info %>% filter(class_id %in% te_class_id)
```

## Prepare PCA plot

```{r}
# human and chimpanzee
gene_hm_chimp <- data$hmchimpDE$normalized_gene_counts %>%
    data.frame() %>%
    filter(rownames(.) %in% gene_df$ensembl_gene_id) #257

te_hm_chimp <- data$hmchimpDE$normalized_te_counts %>%
    data.frame() %>%
    filter(rownames(.) %in% te_list$gene_id) #882

df_hm_chimp <- rbind(gene_hm_chimp, te_hm_chimp) # merge
df_hm_chimp <- df_hm_chimp %>% mutate(Row = rownames(.))

# human and orangutan
gene_hm_oran <- data$hmoranDE$normalized_gene_counts %>%
    data.frame() %>%
    filter(rownames(.) %in% gene_df$ensembl_gene_id) #200

te_hm_oran <- data$hmoranDE$normalized_te_counts %>%
    data.frame() %>%
    filter(rownames(.) %in% te_list$gene_id) #790

df_hm_oran <- rbind(gene_hm_oran, te_hm_oran)
df_hm_oran <- df_hm_oran %>% mutate(Row = rownames(.))

# intersect
combine_df <- full_join(df_hm_chimp, df_hm_oran[,c(10:19)], by="Row") %>%
    mutate(across(everything(), ~ replace_na(.x, 0)))
rownames(combine_df) <- combine_df$Row
combine_df <- combine_df %>% select(-Row)
```

Prepare PCA input
```{r}
combine_long <- combine_df %>%
    rownames_to_column("gene") %>%
    pivot_longer(-gene, names_to="Sample", values_to="Expression") %>%
    mutate(Species = case_when(
        grepl("^h", Sample) ~ "Human",
        grepl("^c", Sample) ~ "Chimp",
        grepl("^o", Sample) ~ "Orangutan"
    ))

combine_wide <- combine_long %>%
    select(Sample, gene, Expression) %>%
    pivot_wider(names_from = Sample, values_from=Expression) %>%
    column_to_rownames("gene")

pca_result <- prcomp(t(combine_wide), scale.=TRUE)

variance_explained <- c(pca_result$sdev^2) / sum(pca_result$sdev^2) * 100

pca_data <- as.data.frame(pca_result$x) %>%
  rownames_to_column("Sample") %>%
  mutate(Species = case_when(
    grepl("^h", Sample) ~ "Human",
    grepl("^c", Sample) ~ "Chimp",
    grepl("^o", Sample) ~ "Orangutan"
  ))

pca_data$Species <- factor(pca_data$Species, levels = c("Human", "Chimp", "Orangutan"))

g_znf_pca <- ggplot(pca_data, aes(x = PC1, y = PC2, fill = Species, label = Sample)) +
  geom_point(size = 4, shape = 21, color="black") +
  geom_text(vjust = -0.5, size=3, check_overlap = TRUE) + # Avoid text overlap
  scale_fill_manual(values = c("Human" = "#e7b7b1", "Chimp" = "#c8eaee", "Orangutan" = "#b2beb5")) +
  labs(title = "", x = "PC1 (24.89%)", y = "PC2 (15.9%)") +
  theme_bw()

ggsave(g_znf_pca, file="../../figures/PCA_KZNFs_TEs.jpg", width=5, height=4, dpi=300)
```

Next, I want to see how many DE TEs, KAP1, and KRAB-ZNFs between species
```{r}
# gene
hmchimp_DE <- data$hmchimpDE$gene_res %>%
    data.frame() %>%
    filter(rownames(.) %in% gene_df$ensembl_gene_id) %>%
    mutate(geneID=rownames(.)) %>%
    left_join(gene_df, join_by(geneID==ensembl_gene_id)) %>%
    filter(abs(log2FoldChange)>=1.5 & padj<0.05) #40

hmoran_DE <- data$hmoranDE$gene_res %>%
    data.frame() %>%
    filter(rownames(.) %in% gene_df$ensembl_gene_id) %>%
    mutate(geneID=rownames(.)) %>%
    left_join(gene_df, join_by(geneID==ensembl_gene_id)) %>%
    filter(abs(log2FoldChange)>=1.5 & padj<0.05) #39

chimporan_DE <- data$chimporanDE$gene_res %>%
   data.frame() %>%
   mutate(ID=rownames(.)) %>%
   left_join(data$ortholog_hmchimp, join_by(ID==compareEnsemblID)) %>% #12898
   filter(refEnsemblID %in% gene_df$ensembl_gene_id) %>%
   filter(abs(log2FoldChange)>=1.5 & padj<0.05) #37
   
       
# TE
hmchimp_TE <- data$hmchimpDE$te_res %>%
    data.frame() %>%
    filter(rownames(.) %in% te_list$gene_id) %>%
    filter(abs(log2FoldChange)>=1.5 & padj<0.05) #91

hmoran_TE <- data$hmoranDE$te_res %>%
    data.frame() %>%
    filter(rownames(.) %in% te_list$gene_id) %>%
    filter(abs(log2FoldChange)>=1.5 & padj<0.05) #94

chimporan_TE <- data$chimporanDE$te_res %>%
    data.frame() %>%
    filter(rownames(.) %in% te_list$gene_id) %>%
    filter(abs(log2FoldChange)>=1.5 & padj<0.05) #93

```

Let us try to merge these DE results into a dataframe
```{r}
# add group
# gene
hmchimp_DE <- hmchimp_DE %>% mutate(group="H_vs_C")
hmoran_DE <- hmoran_DE %>% mutate(group="H_vs_O")
chimporan_DE <- chimporan_DE %>% mutate(group="C_vs_O")
colnames(chimporan_DE)[7] <- "external_gene_name"

select_column <- c("group", "external_gene_name", "baseMean", "log2FoldChange", "padj")

df_DE_gene <- rbind(
    hmchimp_DE[,select_column],
    hmoran_DE[,select_column],
    chimporan_DE[,select_column]
) #116
rownames(df_DE_gene) <- 1:nrow(df_DE_gene)

# TE
hmchimp_TE <- hmchimp_TE %>% mutate(group="H_vs_C", ID=rownames(.))
hmoran_TE <- hmoran_TE %>% mutate(group="H_vs_O", ID=rownames(.))
chimporan_TE <- chimporan_TE %>% mutate(group="C_vs_O", ID=rownames(.))
select_col_name <- c("group", "ID", "baseMean", "log2FoldChange", "padj")

df_DE_te <- rbind(
    hmchimp_TE[,select_col_name],
    hmoran_TE[,select_col_name],
    chimporan_TE[,select_col_name]
) #278
rownames(df_DE_te) <- 1:nrow(df_DE_te)
```

save DE table
```{r}
write.table(df_DE_gene, "../../tables/DE_genes.csv", sep=",", row.names = F)
write.table(df_DE_te, "../../tables/DE_TEs.csv", sep=",", row.names=F)
# use read.csv("tables/DE_TEs.csv") to read
```

