# Analyze ChIP-seq data

1.  Read and merge the files (what is the select criteria?)
2.  Prepare TE annotation files
3.  Do intersect

Load libraries

```{r}
library(twice)
library(dplyr)
data("hg19rmsk_info")

TE_info <- hg19rmsk_info %>%
    filter(class_id %in% c("SINE", "LINE", "DNA", "SVA", "LTR"))

young_TE <- read.csv("../../tables/Dfam_TE_simiiformes.csv")
```

```{r}
# load overlap TE peaks
hm_TE <- read.table("../../peaks/macs3_results/hm_TE.peak", sep="\t")
chimp_TE <- read.table("../../peaks/macs3_results/chimp_TE.peak", sep="\t")
oran_TE <- read.table("../../peaks/macs3_results/oran_TE.peak", sep="\t")
```

Filter only SINE, LINE, DNA, SVA, LTR samples

```{r}
hm_TE_filter <- hm_TE %>% 
    filter(V4 %in% TE_info$gene_id) # 3913

chimp_TE_filter <- chimp_TE %>%
    filter(V4 %in% TE_info$gene_id) # 10300

oran_TE_filter <- oran_TE %>%
    filter(V4 %in% TE_info$gene_id) # 30715

```

See how many of them from the subfamily group Use Upsetplot to have an overview,

```{r}
hm_TE_select <- hm_TE_filter %>%
    count(V4) %>%
    arrange(desc(n)) #246

chimp_TE_select <- chimp_TE_filter %>%
    count(V4) %>%
    arrange(desc(n)) #429

oran_TE_select <- oran_TE_filter %>%
    count(V4) %>%
    arrange(desc(n)) #493
```

Visualize:

```{r}
library(ggplot2)
library(ComplexUpset)

all_TE <- unique(c(hm_TE_select$V4, chimp_TE_select$V4, oran_TE_select$V4)) #589
data <- data.frame(
    Human = all_TE %in% hm_TE_select$V4,
    Chimp = all_TE %in% chimp_TE_select$V4,
    Orangutan = all_TE %in% oran_TE_select$V4
)

rownames(data) <- all_TE

g_upset <- upset(data, c("Human", "Chimp", "Orangutan"))
ggsave(g_upset, filename="../../figures/upset_TE.jpg", dpi=300, width=6, height=4)
```

Add evolutionary age

```{r}
data_age <- data %>%
    mutate(age = ifelse(rownames(.) %in% young_TE$NM, "young", "old"))
write.csv(data_age, file="../../tables/TE_589_intersect.csv")
```

```{r}
intersect_TE <- Reduce(intersect, 
                       list(hm_TE_select$V4, chimp_TE_select$V4, oran_TE_select$V4))

TE_info_intersect <- TE_info %>% 
    filter(gene_id %in% intersect_TE) %>%
    mutate(TE_age = ifelse(gene_id %in% young_TE$NM, "young", "old"))


hm_chimp_intersect <- intersect(hm_TE_select$V4, chimp_TE_select$V4) 
hm_chimp_intersect_no_oran <- setdiff(hm_chimp_intersect, oran_TE_select$V4)
TE_info_onlyHmChimp_noOran <- TE_info %>%
    filter(gene_id %in% hm_chimp_intersect_no_oran) %>%
    mutate(TE_age = ifelse(gene_id %in% young_TE$NM, "young", "old"))

# human specific
hm_specific <- setdiff(hm_TE_select$V4, chimp_TE_select$V4)
hm_specific <- setdiff(hm_specific, oran_TE_select$V4) #13
```

Generate plots for **Figure2B**: (1) peak counts vs. h/c/o (2) TE subfamiliy counts vs. h/c/o

```{r}
library(ggplot2)
library(ggpubr)

# peak counts
df_peak <- data.frame(
    species = factor(c("H", "C", "O"), levels = c("H", "C", "O")),
    peak_count = c(2470, 7301, 12376)
)

g1 <- ggplot(df_peak, aes(x=species, y=peak_count, fill=species)) +
    geom_bar(stat="identity") +
    scale_fill_manual(values=c("H"="#e7b7b1", "C"="#c8eaee", "O"="#b2beb5")) +
    ylab("Peak Counts") +
    xlab("") +
    theme_bw() +
    theme(text = element_text(size=20)) 

```

```{r}
df_TEsubfamily <- data.frame(
    species = factor(c("H", "C", "O"), levels = c("H", "C", "O")),
    te = c(246, 429, 493)
)

g2 <- ggplot(df_TEsubfamily, aes(x=species, y=te, fill=species)) +
    geom_bar(stat="identity") +
    scale_fill_manual(values=c("H"="#e7b7b1", "C"="#c8eaee", "O"="#b2beb5")) +
    ylab("TE subfamily counts") +
    xlab("") +
    theme_bw() +
    theme(text = element_text(size=20)) 
```

```{r}
g_merge <- ggarrange(g1, g2, ncol=2, common.legend = TRUE, legend = "bottom")
ggsave("../../figures/fig2b.jpg", dpi=300, width=8, height=6)
```
