# Prepare input data for MEME-ChIP analysis (v5.5.7)

```{r}
library(dplyr)
```


```{r}
hm <- read.table("../../peaks/macs3_results/human_TE_only.bed", sep="\t") #2077
chimp <- read.table(
    "../../peaks/macs3_results/chimp_TE_only.bed", sep="\t") #5754
oran <- read.table("../../peaks/macs3_results/oran_TE_only.bed", sep="\t") #10098
```

I upload the human_TE_only.bed, chimp_TE_only.bed, and oran_TE_only.bed files to MEME-ChIP platform. 

Then I can download the data from MEME result: `kap1_primate/meme_result`.
The purpose is to get the motifs information from KRAB-ZNFs.

```{r}
human_hocomoco <- read.table('../../meme_result/Human_HOCOMOCO.tsv', 
                            sep='\t', header=TRUE)

human_jaspar <- read.table('../../meme_result/Human_JASPAR.tsv', 
                            sep='\t', header=TRUE)

chimp_jaspar <- read.table('../../meme_result/Chimp_JASPAR.tsv',
                            sep='\t', header=TRUE)

oran_jaspar <- read.table('../../meme_result/Oran_JASPAR.tsv',
                           sep='\t', header=TRUE)
```

Get rows with KRAB-ZNF motif.
```{r}
hm_hocomoco_select <- human_hocomoco[
    apply(human_hocomoco, 1, 
          function(x) any(grepl("ZNF|TRIM28|PRDM9|ZKSCAN", x))), ] #3

hm_jaspar_select <- human_jaspar[
    apply(human_jaspar, 1, 
          function(x) any(grepl("ZNF|TRIM28|PRDM9|ZKSCAN", x))),] #34

chimp_select <- chimp_jaspar[
    apply(chimp_jaspar, 1, function(x) any(grepl("ZNF|TRIM28|PRDM9|ZKSCAN", x))), ] #4

oran_select <- oran_jaspar[
    apply(oran_jaspar, 1, function(x) any(grepl("ZNF|TRIM28|PRDM9|ZKSCAN", x))), ] #12

```

merge dataframe and upload to supplementary tables
```{r}
hm_hocomo <- human_hocomoco %>%
    select(c(2:12)) %>%
    mutate(species = "human")

hm_jaspar <- human_jaspar %>%
    select(c(2:12)) %>%
    mutate(species = "human")

chimp_process <- chimp_select %>%
    select(c(2:12)) %>%
    mutate(species = "chimp")
    
oran_process <- oran_select %>%
    select(c(2:12)) %>%
    mutate(species = "orangutan")

# rbind
df_motif <- rbind(hm_hocomo, hm_jaspar, chimp_process, oran_process)

df_motif <- df_motif[,c(12, seq(1:11))]
rownames(df_motif) <- 1:nrow(df_motif)
write.table(df_motif, file="../../tables/motifs.csv", sep=',', row.names = FALSE)
```


